import { z } from "zod";

export const ConditionSchema = z.object({
  text: z.string(),
  icon: z.string(),
  code: z.number(),
});

export const AirQualitySchema = z.object({
  co: z.number().optional(),
  no2: z.number().optional(),
  o3: z.number().optional(),
  so2: z.number().optional(),
  pm2_5: z.number().optional(),
  pm10: z.number().optional(),
  "us-epa-index": z.number().optional(),
  "gb-defra-index": z.number().optional(),
});

export const HourSchema = z.object({
  time_epoch: z.number(),
  time: z.string(),
  temp_c: z.number(),
  temp_f: z.number(),
  is_day: z.union([z.literal(0), z.literal(1)]),
  condition: ConditionSchema,
  wind_mph: z.number(),
  wind_kph: z.number(),
  wind_degree: z.number(),
  wind_dir: z.string(),
  pressure_mb: z.number(),
  pressure_in: z.number(),
  precip_mm: z.number(),
  precip_in: z.number(),
  snow_cm: z.number(),
  humidity: z.number(),
  cloud: z.number(),
  feelslike_c: z.number(),
  feelslike_f: z.number(),
  windchill_c: z.number(),
  windchill_f: z.number(),
  heatindex_c: z.number(),
  heatindex_f: z.number(),
  dewpoint_c: z.number(),
  dewpoint_f: z.number(),
  will_it_rain: z.number(),
  chance_of_rain: z.number(),
  will_it_snow: z.number(),
  chance_of_snow: z.number(),
  vis_km: z.number(),
  vis_miles: z.number(),
  uv: z.number(),
  gust_mph: z.number(),
  gust_kph: z.number(),
  air_quality: AirQualitySchema.optional(),
  short_rad: z.number().optional(),
  diff_rad: z.number().optional(),
  dni: z.number().optional(),
  gti: z.number().optional(),
});

export const WeatherApiSchema = z.object({
  location: z.object({
    name: z.string(),
    region: z.string(),
    country: z.string(),
    lat: z.number(),
    lon: z.number(),
    tz_id: z.string(),
    localtime_epoch: z.number(),
    localtime: z.string(),
  }),

  current: z.object({
    last_updated_epoch: z.number(),
    last_updated: z.string(),
    temp_c: z.number(),
    temp_f: z.number(),
    is_day: z.union([z.literal(0), z.literal(1)]),
    condition: ConditionSchema,
    wind_mph: z.number(),
    wind_kph: z.number(),
    wind_degree: z.number(),
    wind_dir: z.string(),
    pressure_mb: z.number(),
    pressure_in: z.number(),
    precip_mm: z.number(),
    precip_in: z.number(),
    humidity: z.number(),
    cloud: z.number(),
    feelslike_c: z.number(),
    feelslike_f: z.number(),
    windchill_c: z.number(),
    windchill_f: z.number(),
    heatindex_c: z.number(),
    heatindex_f: z.number(),
    dewpoint_c: z.number(),
    dewpoint_f: z.number(),
    vis_km: z.number(),
    vis_miles: z.number(),
    uv: z.number(),
    gust_mph: z.number(),
    gust_kph: z.number(),
    air_quality: AirQualitySchema.optional(),
    short_rad: z.number().optional(),
    diff_rad: z.number().optional(),
    dni: z.number().optional(),
    gti: z.number().optional(),
  }),

  forecast: z.object({
    forecastday: z.array(
      z.object({
        date: z.string(),
        date_epoch: z.number(),
        day: z.any(),
        astro: z.any(),
        hour: z.array(HourSchema),
      })
    ),
  }),

  alerts: z.object({
    alert: z.array(z.any()),
  }),
});
