name: Deploy

on:
  workflow_run:
    workflows:
      - "Build and Push Changed Docker Images"
      - "Build and Push Docker Images (Manual)"
    types:
      - completed
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted

    steps:
      - name: Deploy on device
        run: |
          cd ${{ secrets.DEVICE_DIR }}
          git pull origin main
          docker compose pull
          docker compose up -d --remove-orphans
          docker image prune -f
